http:
  routers:
    redirect-to-https:
      entryPoints: ["web"]
      rule: "HostRegexp(`{any:.*}`)"
      service: noop
      middlewares:
        - redirect-https

  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"   # Dummy
