entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/config/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "seu-email@dominio.com"
      storage: "acme.json"
      httpChallenge:
        entryPoint: web

# DUCK DNS
# certificatesResolvers:
#   duckdns:
#     acme:
#       email: "seu-email@dominio.com"
#       storage: "acme.json"
#       dnsChallenge:
#         provider: duckdns
#         resolvers:
#           - "8.8.8.8:53"
#           - "1.1.1.1:53"
#         delayBeforeCheck: 30
